namespace CutTheRope.windows
{
	public enum BlendingFactor
	{
		GL_ZERO = 0,
		GL_ONE = 1,
		GL_SRC_COLOR = 768,
		GL_ONE_MINUS_SRC_COLOR = 769,
		GL_SRC_ALPHA = 770,
		GL_ONE_MINUS_SRC_ALPHA = 771,
		GL_DST_ALPHA = 772,
		GL_ONE_MINUS_DST_ALPHA = 773,
		GL_DST_COLOR = 774,
		GL_ONE_MINUS_DST_COLOR = 775,
		GL_SRC_ALPHA_SATURATE = 776
	}
}
